### ISSUE TITLE
Handle print statements in non BEGIN/END blocks

### ISSUE THREAD

**Issue by dspinellis** [gthd/pawk#15]
They should be either prohibited, or, better, their outpout should be stored in memory or in temporary files and then serialized.

**Comment by gthd** [comment]
Hi @dspinellis, can you please provide me with such an example to test against.

**Comment by dspinellis** [comment]
# Trivial implementation
`awk '{print}'` should fail with an error, while `awk 'BEGIN{print "hello "} END {print "world"}' /dev/null` should succeed printing `hello world`.

# More sophisticated implementation
`seq 1 10000 | awk '{print}'` should output the same as `seq 1 10000`.

**Comment by gthd** [comment]
Since print is not parallelizable, shouldn't we restrict its use inside the action statement ?

**Comment by dspinellis** [comment]
This is the trivial implementation. The more sophisticated one involves storing its output and serializing it at the end of the program's operation.

**Comment by gthd** [comment]
I have implemented the trivial solution so far.
